#!/usr/bin/env python3

import argparse
import re
from pathlib import Path

CALLBACK_RE = re.compile(r'^\s*MAKE_CALLBACK_THUNK\(callback_(\d+),\s*(.*),\s*"(.*)"\);\s*$')


def parse_callbacks(text: str):
    callbacks = []
    for line in text.splitlines():
        match = CALLBACK_RE.match(line)
        if match:
            callbacks.append((int(match.group(1)), match.group(2).strip(), match.group(3)))
    if not callbacks:
        raise RuntimeError("No MAKE_CALLBACK_THUNK entries found in generated guest thunk output")
    return callbacks


def write_bridge(path: Path, callbacks):
    lines = [
        "// Generated by extract_guest_bridge.py. Do not edit.",
        "",
    ]
    for index, signature, hash_bytes in callbacks:
        lines.append(f"// {signature}")
        lines.append(f'MAKE_CALLBACK_THUNK(callback_{index}, {signature}, "{hash_bytes}");')
    lines.append("")

    for index, signature, _ in callbacks:
        lines += [
            f"using fex_bridge_signature_{index} = {signature};",
            f'extern "C" uintptr_t fex_bridge_invoker_{index}() {{',
            f"  return reinterpret_cast<uintptr_t>(GetCallerForHostFunction((fex_bridge_signature_{index}*)nullptr));",
            "}",
            f'extern "C" uintptr_t fex_bridge_unpacker_{index}() {{',
            f"  return reinterpret_cast<uintptr_t>(CallbackUnpack<fex_bridge_signature_{index}>::Unpack);",
            "}",
            "",
        ]
    path.write_text("\n".join(lines))


def write_accessors(path: Path, callbacks):
    lines = [
        "// Generated by extract_guest_bridge.py. Do not edit.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "template<typename Signature>",
        "struct FEXResidentBridgeInvoker;",
        "template<typename Signature>",
        "struct FEXResidentBridgeUnpacker;",
        "",
    ]

    for index, signature, _ in callbacks:
        lines += [
            f'extern "C" uintptr_t fex_bridge_invoker_{index}();',
            f'extern "C" uintptr_t fex_bridge_unpacker_{index}();',
            f"using fex_bridge_accessor_signature_{index} = {signature};",
            f"template<> struct FEXResidentBridgeInvoker<fex_bridge_accessor_signature_{index}> {{",
            f"  static fex_bridge_accessor_signature_{index}* Get() {{",
            f"    return reinterpret_cast<fex_bridge_accessor_signature_{index}*>(fex_bridge_invoker_{index}());",
            "  }",
            "};",
            f"template<> struct FEXResidentBridgeUnpacker<fex_bridge_accessor_signature_{index}> {{",
            "  static void (*Get())(uintptr_t, void*) {",
            f"    return reinterpret_cast<void (*)(uintptr_t, void*)>(fex_bridge_unpacker_{index}());",
            "  }",
            "};",
            "",
        ]

    lines += [
        "template<typename Result, typename... Args>",
        "static Result (*FEXGetResidentCallerForHostFunction(Result (*)(Args...)))(Args...) {",
        "  return FEXResidentBridgeInvoker<Result(Args...)>::Get();",
        "}",
        "",
        "template<typename Result, typename... Args>",
        "static void (*FEXGetResidentCallbackUnpacker(Result (*)(Args...)))(uintptr_t, void*) {",
        "  return FEXResidentBridgeUnpacker<Result(Args...)>::Get();",
        "}",
        "",
        "template<typename Target>",
        "static Target* FEXAllocateResidentHostTrampolineForGuestFunction(Target* GuestTarget) {",
        "  return AllocateHostTrampolineForGuestFunction(FEXGetResidentCallbackUnpacker(GuestTarget), GuestTarget);",
        "}",
        "",
    ]
    path.write_text("\n".join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("guest_inl", type=Path)
    parser.add_argument("bridge_inl", type=Path)
    parser.add_argument("accessors_inl", type=Path)
    args = parser.parse_args()

    callbacks = parse_callbacks(args.guest_inl.read_text())
    args.bridge_inl.parent.mkdir(parents=True, exist_ok=True)
    args.accessors_inl.parent.mkdir(parents=True, exist_ok=True)
    write_bridge(args.bridge_inl, callbacks)
    write_accessors(args.accessors_inl, callbacks)
    print(f"extracted {len(callbacks)} resident bridge signatures")


if __name__ == "__main__":
    main()
