from pathlib import Path


def replace_one(path: str, old: str, new: str) -> None:
    p = Path(path)
    s = p.read_text()
    count = s.count(old)
    assert count == 1, (path, count, old[:160])
    p.write_text(s.replace(old, new, 1))


# Generic nested function-pointer member annotation, previously proved on DRM
# and CUDA. A callback-bearing input record is copied on the guest stack;
# callback fields receive partial host trampolines there and are finalized by
# generated host code after ordinary record repacking.
replace_one(
    'ThunkLibs/include/common/GeneratorInterface.h',
    'struct custom_repack {};\n',
    '''struct custom_repack {};\n\n// Research prototype: mark a function-pointer structure member as a guest\n// callback. callback_member conversion is generated by thunkgen.\nstruct callback_member {};\n''')

replace_one(
    'ThunkLibs/Generator/analysis.h',
    '''    // Set of members (identified by their field name) with custom repacking\n    std::unordered_set<std::string> custom_repacked_members;\n\n    bool UsesCustomRepackFor(const clang::FieldDecl* member) const {\n      return custom_repacked_members.contains(member->getNameAsString());\n    }\n    bool UsesCustomRepackFor(const std::string& member_name) const {\n      return custom_repacked_members.contains(member_name);\n    }\n''',
    '''    // Set of members (identified by their field name) with custom repacking.\n    // callback_members are included here because automatic layout conversion\n    // must leave their raw function-pointer values for callback-specific code.\n    std::unordered_set<std::string> custom_repacked_members;\n    std::unordered_set<std::string> callback_members;\n\n    bool UsesCustomRepackFor(const clang::FieldDecl* member) const {\n      return custom_repacked_members.contains(member->getNameAsString());\n    }\n    bool UsesCustomRepackFor(const std::string& member_name) const {\n      return custom_repacked_members.contains(member_name);\n    }\n    bool UsesCallbackMemberFor(const clang::FieldDecl* member) const {\n      return callback_members.contains(member->getNameAsString());\n    }\n    bool HasManualCustomRepack() const {\n      for (const auto& member : custom_repacked_members) {\n        if (!callback_members.contains(member)) {\n          return true;\n        }\n      }\n      return false;\n    }\n''')

replace_one(
    'ThunkLibs/Generator/analysis.cpp',
    '''        } else if (auto annotated_member = llvm::dyn_cast<clang::FieldDecl>(template_args[0].getAsDecl())) {\n          if (decl->getNumBases() != 1 || decl->bases_begin()->getType().getAsString() != "fexgen::custom_repack") {\n            throw report_error(template_arg_loc, "Unsupported member annotation(s)");\n          }\n\n          // Get or add parent type to list of structure types\n#if CLANG_VERSION_MAJOR >= 22\n          auto parent_qt = context.getTagType(clang::ElaboratedTypeKeyword::None, std::nullopt, annotated_member->getParent(), false);\n          auto repack_info_it = types.emplace(context.getCanonicalType(parent_qt).getTypePtr(), RepackedType {}).first;\n#else\n          auto repack_info_it = types.emplace(context.getCanonicalType(annotated_member->getParent()->getTypeForDecl()), RepackedType {}).first;\n#endif\n          if (repack_info_it->second.assumed_compatible) {\n            throw report_error(template_arg_loc, "May not annotate members of opaque types");\n          }\n          // Add member to its list of members\n          repack_info_it->second.custom_repacked_members.insert(annotated_member->getNameAsString());\n''',
    '''        } else if (auto annotated_member = llvm::dyn_cast<clang::FieldDecl>(template_args[0].getAsDecl())) {\n          if (decl->getNumBases() != 1) {\n            throw report_error(template_arg_loc, "Unsupported member annotation(s)");\n          }\n          auto member_annotation = decl->bases_begin()->getType().getAsString();\n          if (member_annotation != "fexgen::custom_repack" && member_annotation != "fexgen::callback_member") {\n            throw report_error(template_arg_loc, "Unsupported member annotation(s)");\n          }\n\n          // Get or add parent type to list of structure types\n#if CLANG_VERSION_MAJOR >= 22\n          auto parent_qt = context.getTagType(clang::ElaboratedTypeKeyword::None, std::nullopt, annotated_member->getParent(), false);\n          auto repack_info_it = types.emplace(context.getCanonicalType(parent_qt).getTypePtr(), RepackedType {}).first;\n#else\n          auto repack_info_it = types.emplace(context.getCanonicalType(annotated_member->getParent()->getTypeForDecl()), RepackedType {}).first;\n#endif\n          if (repack_info_it->second.assumed_compatible) {\n            throw report_error(template_arg_loc, "May not annotate members of opaque types");\n          }\n\n          auto member_name = annotated_member->getNameAsString();\n          repack_info_it->second.custom_repacked_members.insert(member_name);\n\n          if (member_annotation == "fexgen::callback_member") {\n            if (!annotated_member->getType()->isFunctionPointerType()) {\n              throw report_error(template_arg_loc, "callback_member requires a function-pointer field");\n            }\n            auto funcptr = annotated_member->getType()->getPointeeType()->getAs<clang::FunctionProtoType>();\n            if (!funcptr) {\n              throw report_error(template_arg_loc, "callback_member requires a prototype function-pointer field");\n            }\n            if (funcptr->isVariadic()) {\n              throw report_error(template_arg_loc, "Variadic callback members are not supported by this prototype");\n            }\n            repack_info_it->second.callback_members.insert(member_name);\n            thunked_funcptrs["callback_member_" + annotated_member->getQualifiedNameAsString()] =\n              std::pair {context.getCanonicalType(funcptr), no_param_annotations};\n          }\n''')

replace_one(
    'ThunkLibs/Generator/gen.cpp',
    '''    // Forward-declare user-provided repacking functions\n    if (type_repack_info.custom_repacked_members.empty()) {\n      fmt::print(file, "void fex_apply_custom_repacking_entry(host_layout<{}>& source, const guest_layout<{}>& from) {{\\n", struct_name, struct_name);\n      fmt::print(file, "}}\\n");\n      fmt::print(file, "bool fex_apply_custom_repacking_exit(guest_layout<{}>& into, const host_layout<{}>& from) {{\\n", struct_name, struct_name);\n      fmt::print(file, "  return false;\\n");\n      fmt::print(file, "}}\\n");\n''',
    '''    // Forward-declare user-provided repacking functions. callback_member\n    // fields are filled by generated thunk unpacking code and do not by\n    // themselves require handwritten parent-record repacking.\n    if (!type_repack_info.HasManualCustomRepack()) {\n      fmt::print(file, "void fex_apply_custom_repacking_entry(host_layout<{}>& source, const guest_layout<{}>& from) {{\\n", struct_name, struct_name);\n      fmt::print(file, "}}\\n");\n      fmt::print(file, "bool fex_apply_custom_repacking_exit(guest_layout<{}>& into, const host_layout<{}>& from) {{\\n", struct_name, struct_name);\n      fmt::print(file, "  return {};\\n", type_repack_info.callback_members.empty() ? "false" : "true");\n      fmt::print(file, "}}\\n");\n''')

replace_one(
    'ThunkLibs/Generator/gen.cpp',
    '''  auto get_callback_name = [](std::string_view function_name, unsigned param_index) -> std::string {\n    return fmt::format("{}CBFN{}", function_name, param_index);\n  };\n\n  // Files used guest-side\n''',
    '''  auto get_callback_name = [](std::string_view function_name, unsigned param_index) -> std::string {\n    return fmt::format("{}CBFN{}", function_name, param_index);\n  };\n\n  auto get_callback_struct_info = [&](clang::QualType type) -> const RepackedType* {\n    if (!type->isPointerType()) {\n      return nullptr;\n    }\n    auto pointee = type->getPointeeType();\n    if (!pointee->isStructureType()) {\n      return nullptr;\n    }\n    auto key = context.getCanonicalType(pointee.getTypePtr());\n    auto it = types.find(key);\n    if (it == types.end() || it->second.callback_members.empty()) {\n      return nullptr;\n    }\n    return &it->second;\n  };\n\n  // Files used guest-side\n''')

replace_one(
    'ThunkLibs/Generator/gen.cpp',
    '''      file << "  } args;\\n";\n\n      for (std::size_t idx = 0; idx < data.param_types.size(); ++idx) {\n        auto cb = data.callbacks.find(idx);\n\n        file << "  args.a_" << idx << " = ";\n        if (cb == data.callbacks.end() || cb->second.is_stub) {\n          file << "a_" << idx << ";\\n";\n        } else {\n          // Before passing guest function pointers to the host, wrap them in a host-callable trampoline\n          fmt::print(file, "AllocateHostTrampolineForGuestFunction(a_{});\\n", idx);\n        }\n      }\n''',
    '''      file << "  } args;\\n";\n\n      // callback_member records are copied on the guest stack so replacing\n      // callback fields never mutates caller-owned input.\n      for (std::size_t idx = 0; idx < data.param_types.size(); ++idx) {\n        auto callback_struct = get_callback_struct_info(data.param_types[idx]);\n        if (!callback_struct) {\n          continue;\n        }\n        auto pointee = data.param_types[idx]->getPointeeType();\n        auto* struct_decl = pointee->getAsStructureType()->getDecl();\n        fmt::print(file, "  {} fex_callback_copy_{} {{}};\\n", get_type_name(context, pointee.getTypePtr()), idx);\n        fmt::print(file, "  if (a_{}) {{\\n", idx);\n        fmt::print(file, "    fex_callback_copy_{} = *a_{};\\n", idx, idx);\n        for (auto* member : struct_decl->fields()) {\n          if (!callback_struct->UsesCallbackMemberFor(member)) {\n            continue;\n          }\n          auto member_name = member->getNameAsString();\n          fmt::print(file, "    fex_callback_copy_{}.{} = AllocateHostTrampolineForGuestFunction(a_{}->{});\\n", idx, member_name, idx,\n                     member_name);\n        }\n        fmt::print(file, "  }}\\n");\n      }\n\n      for (std::size_t idx = 0; idx < data.param_types.size(); ++idx) {\n        auto cb = data.callbacks.find(idx);\n        auto callback_struct = get_callback_struct_info(data.param_types[idx]);\n\n        file << "  args.a_" << idx << " = ";\n        if (callback_struct) {\n          fmt::print(file, "a_{} ? &fex_callback_copy_{} : nullptr;\\n", idx, idx);\n        } else if (cb == data.callbacks.end() || cb->second.is_stub) {\n          file << "a_" << idx << ";\\n";\n        } else {\n          // Before passing guest function pointers to the host, wrap them in a host-callable trampoline\n          fmt::print(file, "AllocateHostTrampolineForGuestFunction(a_{});\\n", idx);\n        }\n      }\n''')

replace_one(
    'ThunkLibs/Generator/gen.cpp',
    '''        } else if (pointee_compat == TypeCompatibility::Repackable) {\n          // TODO: Require opt-in for this to be emitted since it's single-element only; otherwise, pointers-to-arrays arguments will cause stack trampling\n          fmt::print(file, "  auto a_{} = make_repack_wrapper<{}>(args->a_{});\\n", param_idx,\n                     get_type_name_with_nonconst_pointee(param_type), param_idx);\n        } else {\n''',
    '''        } else if (pointee_compat == TypeCompatibility::Repackable) {\n          // TODO: Require opt-in for this to be emitted since it's single-element only; otherwise, pointers-to-arrays arguments will cause stack trampling\n          fmt::print(file, "  auto a_{} = make_repack_wrapper<{}>(args->a_{});\\n", param_idx,\n                     get_type_name_with_nonconst_pointee(param_type), param_idx);\n\n          if (auto callback_struct = get_callback_struct_info(param_type)) {\n            auto pointee = param_type->getPointeeType();\n            auto* struct_decl = pointee->getAsStructureType()->getDecl();\n            fmt::print(file, "  if (a_{}.data) {{\\n", param_idx);\n            for (auto* member : struct_decl->fields()) {\n              if (!callback_struct->UsesCallbackMemberFor(member)) {\n                continue;\n              }\n              auto member_name = member->getNameAsString();\n              fmt::print(file, "    auto fex_callback_{}_{} = args->a_{}.get_pointer()->data.{};\\n", param_idx, member_name, param_idx,\n                         member_name);\n              fmt::print(file, "    FinalizeHostTrampolineForGuestFunction(fex_callback_{}_{});\\n", param_idx, member_name);\n              fmt::print(file,\n                         "    a_{}.data->data.{} = reinterpret_cast<decltype(a_{}.data->data.{})>(uintptr_t {{ fex_callback_{}_{}.data }});\\n",\n                         param_idx, member_name, param_idx, member_name, param_idx, member_name);\n            }\n            fmt::print(file, "  }}\\n");\n          }\n        } else {\n''')

# Replace Vulkan's opaque allocator record with mixed generated/manual member
# handling. pUserData is ordinary pointer translation; the five PFN members are
# generated callbacks. The callback argument enums must be registered so host
# callback unpacking can project them.
replace_one(
    'ThunkLibs/libvulkan/libvulkan_interface.cpp',
    '''// TODO: Should not be opaque, but it's usually NULL anyway. Supporting the contained function pointers will need more work.\ntemplate<>\nstruct fex_gen_type<VkAllocationCallbacks> : fexgen::opaque_type {};''',
    '''// Linux Fieldwork research: generate ABI conversion for allocator callback members.\ntemplate<>\nstruct fex_gen_type<VkSystemAllocationScope> {};\ntemplate<>\nstruct fex_gen_type<VkInternalAllocationType> {};\ntemplate<>\nstruct fex_gen_type<VkAllocationCallbacks> {};\ntemplate<>\nstruct fex_gen_config<&VkAllocationCallbacks::pUserData> : fexgen::custom_repack {};\ntemplate<>\nstruct fex_gen_config<&VkAllocationCallbacks::pfnAllocation> : fexgen::callback_member {};\ntemplate<>\nstruct fex_gen_config<&VkAllocationCallbacks::pfnReallocation> : fexgen::callback_member {};\ntemplate<>\nstruct fex_gen_config<&VkAllocationCallbacks::pfnFree> : fexgen::callback_member {};\ntemplate<>\nstruct fex_gen_config<&VkAllocationCallbacks::pfnInternalAllocation> : fexgen::callback_member {};\ntemplate<>\nstruct fex_gen_config<&VkAllocationCallbacks::pfnInternalFree> : fexgen::callback_member {};''')

# Existing custom-member machinery handles the data pointer; callback ABI
# conversion stays generated. Returning true suppresses exit copyback into the
# caller's const VkAllocationCallbacks object.
replace_one(
    'ThunkLibs/libvulkan/Host.cpp',
    '''static void fexfn_impl_libvulkan_Vulkan_SetGuestXDisplayString(uintptr_t GuestTarget, uintptr_t GuestUnpacker) {\n  MakeHostTrampolineForGuestFunctionAt(GuestTarget, GuestUnpacker, &x11_manager.GuestXDisplayString);\n}\n''',
    '''static void fexfn_impl_libvulkan_Vulkan_SetGuestXDisplayString(uintptr_t GuestTarget, uintptr_t GuestUnpacker) {\n  MakeHostTrampolineForGuestFunctionAt(GuestTarget, GuestUnpacker, &x11_manager.GuestXDisplayString);\n}\n\nvoid fex_custom_repack_entry(host_layout<VkAllocationCallbacks>& into, const guest_layout<VkAllocationCallbacks>& from) {\n  into.data.pUserData = const_cast<void*>(from.data.pUserData.force_get_host_pointer());\n}\n\nbool fex_custom_repack_exit(guest_layout<VkAllocationCallbacks>&, const host_layout<VkAllocationCallbacks>&) {\n  return true;\n}\n''')

# The full derived Vulkan sidecar previously had one accessor specialization per
# MAKE_CALLBACK_THUNK entry. callback_member can register sibling fields with
# identical signatures (the two Vulkan internal allocation notifications are a
# concrete example), so deduplicate by canonical emitted signature before
# producing bridge callbacks/accessors.
replace_one(
    'ThunkLibs/Generator/extract_guest_bridge.py',
    '''def clean_prefix(prefix: str) -> str:\n''',
    '''def deduplicate_callbacks(callbacks):\n    unique = []\n    seen = {}\n    for callback in callbacks:\n        index, signature, hash_bytes = callback\n        previous = seen.get(signature)\n        if previous is None:\n            seen[signature] = callback\n            unique.append(callback)\n            continue\n        if previous[2] != hash_bytes:\n            raise RuntimeError(\n                f"Same callback signature emitted with different hashes: {signature}: {previous[2]} vs {hash_bytes}")\n    return unique\n\n\ndef clean_prefix(prefix: str) -> str:\n''')

replace_one(
    'ThunkLibs/Generator/extract_guest_bridge.py',
    '''    callbacks = parse_callbacks(args.guest_inl.read_text())\n    args.bridge_inl.parent.mkdir(parents=True, exist_ok=True)\n''',
    '''    raw_callbacks = parse_callbacks(args.guest_inl.read_text())\n    callbacks = deduplicate_callbacks(raw_callbacks)\n    args.bridge_inl.parent.mkdir(parents=True, exist_ok=True)\n''')

replace_one(
    'ThunkLibs/Generator/extract_guest_bridge.py',
    '''    print(f"extracted {len(callbacks)} resident bridge signatures for {prefix}")\n''',
    '''    print(f"extracted {len(callbacks)} unique resident bridge signatures from {len(raw_callbacks)} entries for {prefix}")\n''')

print('generated VkAllocationCallbacks callback_member + resident bridge dedup applied')
