#!/usr/bin/env python3
from pathlib import Path

p = Path('ThunkLibs/GuestLibs/CMakeLists.txt')
s = p.read_text()
anchor = '''endfunction()\n\n# These thunks only support 64-bit\n'''
helper = '''endfunction()\n\n# Linux Fieldwork research helper: package a small process-resident guest bridge\n# next to one ordinary unloadable guest thunk wrapper. Lifetime/role selection\n# remains in thunkgen and library-specific code; this helper only wires targets.\nfunction(add_guest_bridge BRIDGE_NAME SONAME)\n  set(options)\n  set(one_value_args OUTPUT_NAME WRAPPER_TARGET GENERATOR)\n  set(multi_value_args DEP_TARGETS INCLUDE_DIRS)\n  cmake_parse_arguments(BRIDGE "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})\n\n  if (TARGET lib${BRIDGE_NAME}-guest-deps)\n    message(FATAL_ERROR "Guest bridge dependency target lib${BRIDGE_NAME}-guest-deps already exists")\n  endif()\n\n  add_library(lib${BRIDGE_NAME}-guest-deps INTERFACE)\n  target_include_directories(lib${BRIDGE_NAME}-guest-deps INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/../include")\n  if (BRIDGE_INCLUDE_DIRS)\n    target_include_directories(lib${BRIDGE_NAME}-guest-deps INTERFACE ${BRIDGE_INCLUDE_DIRS})\n  endif()\n  foreach(dep IN LISTS BRIDGE_DEP_TARGETS)\n    target_link_libraries(lib${BRIDGE_NAME}-guest-deps INTERFACE ${dep})\n  endforeach()\n\n  add_guest_lib(${BRIDGE_NAME} "${SONAME}")\n\n  if (BRIDGE_OUTPUT_NAME)\n    set_target_properties(${BRIDGE_NAME}-guest PROPERTIES OUTPUT_NAME "${BRIDGE_OUTPUT_NAME}")\n  endif()\n\n  if (TARGET_TYPE STREQUAL "SHARED")\n    target_link_options(${BRIDGE_NAME}-guest PRIVATE "LINKER:-z,nodelete")\n  endif()\n\n  if (BRIDGE_GENERATOR)\n    if (NOT TARGET ${BRIDGE_GENERATOR}-guest-bridge-gen)\n      message(FATAL_ERROR "Guest bridge generator target ${BRIDGE_GENERATOR}-guest-bridge-gen does not exist")\n    endif()\n    add_dependencies(${BRIDGE_NAME}-guest ${BRIDGE_GENERATOR}-guest-bridge-gen)\n  endif()\n\n  if (BRIDGE_WRAPPER_TARGET)\n    if (NOT TARGET ${BRIDGE_WRAPPER_TARGET})\n      message(FATAL_ERROR "Guest bridge wrapper target ${BRIDGE_WRAPPER_TARGET} does not exist")\n    endif()\n    target_link_libraries(${BRIDGE_WRAPPER_TARGET} PRIVATE ${BRIDGE_NAME}-guest)\n    if (BRIDGE_GENERATOR)\n      add_dependencies(${BRIDGE_WRAPPER_TARGET} ${BRIDGE_GENERATOR}-guest-bridge-gen)\n    endif()\n  endif()\nendfunction()\n\n# These thunks only support 64-bit\n'''
assert s.count(anchor) == 1, s.count(anchor)
p.write_text(s.replace(anchor, helper, 1))
print('Applied common per-library guest bridge CMake helper')
